version: "2"
modules-download-mode: readonly
run:
  tests: false
linters:
  enable:
    - govet
    - staticcheck
    - unused
    - contextcheck
    - goconst
    - gosec
    - testifylint
    - errcheck
    - revive
    - mnd
    - bodyclose

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: import-shadowing
output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  sort-results: true