version: "2"

run:
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - contextcheck
    - goconst
    - gosec
    - mnd
    - testifylint
    - govet
    - staticcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  show-stats: false